#!/usr/bin/env python
from typing import Any, Optional

class SettingsManager:
    def __init__(self, name: str, settings_directory: Optional[str] = None) -> None: ...
    def read(self): ...
    def commit(self): ...
    def getSetting(self, key: str, default: Any) -> Any: ...
    def setSetting(self, key: str, value: Any): ...
